"""add_science_class_support

Revision ID: 77fb52a63678
Revises: add_student_model
Create Date: 2025-12-27 23:43:16.252709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fb52a63678'
down_revision: Union[str, None] = 'add_student_model'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    class_type_enum = sa.Enum('social_science', 'science', name='classtypeenum')
    class_type_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('students', sa.Column('class_type', class_type_enum, nullable=False, server_default='social_science'))
    op.add_column('students', sa.Column('chemistry_score', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('students', sa.Column('physics_score', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('students', sa.Column('biology_score', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('students', sa.Column('physical_education_score', sa.Float(), nullable=True, server_default='0.0'))
    op.add_column('students', sa.Column('chemistry_max', sa.Float(), nullable=True, server_default='75.0'))
    op.add_column('students', sa.Column('physics_max', sa.Float(), nullable=True, server_default='75.0'))
    op.add_column('students', sa.Column('biology_max', sa.Float(), nullable=True, server_default='75.0'))
    op.add_column('students', sa.Column('physical_education_max', sa.Float(), nullable=True, server_default='75.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'physical_education_max')
    op.drop_column('students', 'biology_max')
    op.drop_column('students', 'physics_max')
    op.drop_column('students', 'chemistry_max')
    op.drop_column('students', 'physical_education_score')
    op.drop_column('students', 'biology_score')
    op.drop_column('students', 'physics_score')
    op.drop_column('students', 'chemistry_score')
    op.drop_column('students', 'class_type')
    # Drop the enum type
    sa.Enum(name='classtypeenum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
